FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["SCNCORE_ORION_RMM_Web_Console.csproj", "."]

# Linux hedefi için restore
RUN dotnet restore "./SCNCORE_ORION_RMM_Web_Console.csproj"

COPY . .
WORKDIR "/src/."

# DefineConstants ekleyerek Linux build
RUN dotnet build "SCNCORE_ORION_RMM_Web_Console.csproj" -c Release -o /app/build -p:DefineConstants="LINUX"

FROM build AS publish
RUN dotnet publish "SCNCORE_ORION_RMM_Web_Console.csproj" -c Release -o /app/publish -p:DefineConstants="LINUX" /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SCNCORE_ORION_RMM_Web_Console.dll"]